# -*- coding: utf-8 -*-
"""demo_crop_geometry.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dy85R--TBrEzV6TKF0OH2kNwl6lXWwhC
"""

import open3d as o3d

def demo_crop_geometry(point_cloud):
    o3d.visualization.draw_geometries_with_editing([point_cloud])

if __name__ == "__main__":
    point_cloud = o3d.geometry.PointCloud()  # Load or create a point cloud
    demo_crop_geometry(point_cloud)