# -*- coding: utf-8 -*-
"""data_preparation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1by4JiWMJ7NSRHacPoaM-wIQRYbts9gCV
"""

import pandas as pd

def load_and_prepare_data(file_path, timestamp_column, sample_prefix):
    df = pd.read_csv(file_path)
    df[timestamp_column] = pd.to_datetime(df[timestamp_column])
    df.set_index(timestamp_column, inplace=True)

    sample_columns = [col for col in df.columns if col.startswith(sample_prefix)]

    return df, sample_columns